### ISSUE TITLE
Several errors

### ISSUE THREAD

**Issue by k-wax** [tiziw/iuvolt#3]
/etc/iuvolt.cfg should (probably) not contain more than one line after reinstalling/updating

root@arch ~ # cat /etc/iuvolt.cfg 
voltages=(-100)
voltages=(0 0 0)
voltages=(0 0 0)

root@arch ~ # systemctl status systemd-iuvolt.service 
● systemd-iuvolt.service - Undervolt cpu
   Loaded: loaded (/etc/systemd/system/systemd-iuvolt.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Tue 2018-01-23 10:52:52 EET; 26min ago
 Main PID: 25309 (code=exited, status=0/SUCCESS)

Jan 23 10:52:52 arch iuvolt[25309]: wrmsr: open: No such file or directory
Jan 23 10:52:52 arch iuvolt[25309]: rdmsr: open: No such file or directory
Jan 23 10:52:52 arch iuvolt[25309]: /usr/bin/iuvolt: line 49: [: ==: unary operator expected
Jan 23 10:52:52 arch iuvolt[25309]: wrote failed, got:
Jan 23 10:52:52 arch iuvolt[25328]: Loaded config! CPU Core : -100mV,
Jan 23 10:52:52 arch iuvolt[25328]: wrmsr: open: No such file or directory
Jan 23 10:52:52 arch iuvolt[25328]: wrmsr: open: No such file or directory
Jan 23 10:52:52 arch iuvolt[25328]: rdmsr: open: No such file or directory
Jan 23 10:52:52 arch iuvolt[25328]: /usr/bin/iuvolt: line 49: [: ==: unary operator expected
Jan 23 10:52:52 arch iuvolt[25328]: wrote failed, got:

root@arch ~ # iuvolt -90
wrmsr: open: No such file or directory
wrmsr: open: No such file or directory
rdmsr: open: No such file or directory
/usr/bin/iuvolt: line 49: [: ==: unary operator expected
wrote failed, got:

This worked better a few days ago. I'll do a system upgrade and reboot to see if it has any effect.

**Comment by k-wax** [comment]
Still the same behaviour.

Arch linux
Linux arch 4.14.14-1-ck-haswell #1 SMP PREEMPT Wed Jan 17 18:41:53 EST 2018 x86_64 GNU/Linux
Core i5-4300u

**Comment by k-wax** [comment]
Still the same behaviour.

Arch linux
Linux arch 4.14.14-1-ck-haswell #1 SMP PREEMPT Wed Jan 17 18:41:53 EST 2018 x86_64 GNU/Linux
Core i5-4300u

Same with Arch default kernel

**Comment by kevcenteno** [comment]
Ubuntu 18.04 - Kernel 4.15.0-13-generic

I'm seeing this behaviour on startup, but runs fine if run manually.  You can see the messages in `journalctl`.

**Comment by kevcenteno** [comment]
It seems that `msr` isn't loaded at startup
